### ISSUE TITLE
App Crashes on Android

### ISSUE THREAD

**Issue by imhassan** [wymsee/cordova-imagePicker#86]
Sometime After selecting images from Gallery App crashes. Stack trace on goolge-play is below.

Plugin version: 1.0.6
Android version:  4.2
Device: Honor3 (hwH30-U10)

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.NullPointerException
at com.synconset.MultiImageChooserActivity$ResizeImagesTask.storeImage(MultiImageChooserActivity.java:627)
at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:542)
at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:485)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)

Could someone point me what to do to fix this issue. Its only on android, IOS version is working fine.

**Comment by MrPro100** [comment]
+ 1
I have the same issue. I tested on android 4.2 and 4.3


Stack Trace
_________________________________
0	java.lang.RuntimeException: An error occured while executing doInBackground()
1		at android.os.AsyncTask$3.done(AsyncTask.java:299)
2		at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
3		at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
4		at java.util.concurrent.FutureTask.run(FutureTask.java:239)
5		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
6		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
7		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
8		at java.lang.Thread.run(Thread.java:841)
9	Caused by: java.lang.IllegalArgumentException: prefix must be at least 3 characters
10		at java.io.File.createTempFile(File.java:1000)
11		at java.io.File.createTempFile(File.java:970)
12		at com.synconset.MultiImageChooserActivity$ResizeImagesTask.storeImage(MultiImageChooserActivity.java:620)
13		at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:540)
14		at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:483)
15		at android.os.AsyncTask$2.call(AsyncTask.java:287)
16		at java.util.concurrent.FutureTask.run(FutureTask.java:234)
17		... 4 more
18	java.lang.IllegalArgumentException: prefix must be at least 3 characters
19		at java.io.File.createTempFile(File.java:1000)
20		at java.io.File.createTempFile(File.java:970)
21		at com.synconset.MultiImageChooserActivity$ResizeImagesTask.storeImage(MultiImageChooserActivity.java:620)
22		at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:540)
23		at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:483)
24		at android.os.AsyncTask$2.call(AsyncTask.java:287)
25		at java.util.concurrent.FutureTask.run(FutureTask.java:234)
26		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
27		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
28		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
29		at java.lang.Thread.run(Thread.java:841)


Threads
_________________________________
Thread: Chrome_IOThread
0	dalvik.system.NativeStart.run(Native Method)

Thread: TXN Thread
0	java.lang.Object.wait(Native Method)
1	java.lang.Object.wait(Object.java:364)
2	android.os.ConditionVariable.block(ConditionVariable.java:97)
3	java.lang.Thread.run(Thread.java:841)

Thread: AsyncTask #5
0	java.lang.Object.wait(Native Method)
1	java.lang.Thread.parkFor(Thread.java:1205)
2	sun.misc.Unsafe.park(Unsafe.java:325)
3	java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
4	java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
5	java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
6	java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
7	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
8	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
9	java.lang.Thread.run(Thread.java:841)

**Comment by MrPro100** [comment]
Is there anyone alive?

**Comment by imhassan** [comment]
No response about this issue yet!

**Comment by morfair** [comment]
This app do not suppoer more?

**Comment by montaserfzy** [comment]
The same issue duplicated in Android Version 4.4

**Comment by DMcNamara** [comment]
Fixed with merge of https://github.com/wymsee/cordova-imagePicker/pull/95

**Comment by montaserfzy** [comment]
Issue still on android 
Scenario: When open image piker directly app crashing..
